apiVersion: v1
kind: Service
metadata:
  name: kronicle-service
spec:
  selector:
    app: kronicle-service
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 8090
    - name: management
      protocol: TCP
      port: 81
      targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: kronicle-app
spec:
  selector:
    app: kronicle-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
